version: "3"

services:
  postgres:
    image: postgres:14
    volumes:
      - ./_docker_volumes/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python3 manage.py collectstatic --noinput &&
             python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
